# Site settings
title: Hedge Fund Startup
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/hedgefundstartup" # the subpath of your site, e.g. /blog/
url: "http://www.hedgefundstartup.co" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

permalink: pretty

# Build settings
highlighter: true
markdown: kramdown

# SASS settings
sass:
sass_dir: _sass
style: :compressed
